/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Fri Feb 28 14:33:11 2020. */

#ifndef PB_TFCPROTO_RUNTIME_CONFIG_V1_PB_H_INCLUDED
#define PB_TFCPROTO_RUNTIME_CONFIG_V1_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _tfcproto_ControlMode {
    tfcproto_ControlMode_MODE_TBL = 0,
    tfcproto_ControlMode_MODE_PID = 1,
    tfcproto_ControlMode_MODE_FIXED = 2,
    tfcproto_ControlMode_MODE_OFF = 3
} tfcproto_ControlMode;
#define _tfcproto_ControlMode_MIN tfcproto_ControlMode_MODE_TBL
#define _tfcproto_ControlMode_MAX tfcproto_ControlMode_MODE_OFF
#define _tfcproto_ControlMode_ARRAYSIZE ((tfcproto_ControlMode)(tfcproto_ControlMode_MODE_OFF+1))

typedef enum _tfcproto_ControlSource {
    tfcproto_ControlSource_SENSOR_WATER_SUPPLY_TEMP = 0,
    tfcproto_ControlSource_SENSOR_WATER_RETURN_TEMP = 1,
    tfcproto_ControlSource_SENSOR_CASE_TEMP = 2,
    tfcproto_ControlSource_SENSOR_AUX1_TEMP = 3,
    tfcproto_ControlSource_SENSOR_AUX2_TEMP = 4,
    tfcproto_ControlSource_VIRTUAL_DELTA_TEMP = 5
} tfcproto_ControlSource;
#define _tfcproto_ControlSource_MIN tfcproto_ControlSource_SENSOR_WATER_SUPPLY_TEMP
#define _tfcproto_ControlSource_MAX tfcproto_ControlSource_VIRTUAL_DELTA_TEMP
#define _tfcproto_ControlSource_ARRAYSIZE ((tfcproto_ControlSource)(tfcproto_ControlSource_VIRTUAL_DELTA_TEMP+1))

/* Struct definitions */
typedef struct _tfcproto_PIDStepV1 {
    uint32_t pct;
    uint32_t delay;
    uint32_t case_temp_delta;
/* @@protoc_insertion_point(struct:tfcproto_PIDStepV1) */
} tfcproto_PIDStepV1;

typedef struct _tfcproto_TableConfigV1_TableEntryV1 {
    uint32_t temp;
    uint32_t pct;
/* @@protoc_insertion_point(struct:tfcproto_TableConfigV1_TableEntryV1) */
} tfcproto_TableConfigV1_TableEntryV1;

typedef struct _tfcproto_PIDConfigV1 {
    uint32_t pwm_percent_min;
    uint32_t pwm_percent_max1;
    uint32_t pwm_percent_max2;
    uint32_t setpoint;
    uint32_t setpoint_min;
    uint32_t setpoint_max;
    uint32_t gain_p;
    uint32_t gain_i;
    uint32_t gain_d;
    bool adaptive_sp;
    bool adaptive_sp_check_case_temp;
    uint32_t adaptive_sp_step_size;
    tfcproto_PIDStepV1 adaptive_sp_step_down;
    tfcproto_PIDStepV1 adaptive_sp_step_up;
/* @@protoc_insertion_point(struct:tfcproto_PIDConfigV1) */
} tfcproto_PIDConfigV1;

typedef struct _tfcproto_TableConfigV1 {
    tfcproto_TableConfigV1_TableEntryV1 entries[10];
/* @@protoc_insertion_point(struct:tfcproto_TableConfigV1) */
} tfcproto_TableConfigV1;

typedef struct _tfcproto_FanConfigV1 {
    uint32_t pin_pwm;
    uint32_t pin_rpm;
    tfcproto_ControlMode mode;
    tfcproto_ControlSource source;
    uint32_t ratio;
    tfcproto_TableConfigV1 tbl;
/* @@protoc_insertion_point(struct:tfcproto_FanConfigV1) */
} tfcproto_FanConfigV1;

typedef struct _tfcproto_SensorConfigV1 {
    uint32_t pin;
    uint32_t beta;
    uint32_t series_r;
    uint32_t nominal_r;
    tfcproto_PIDConfigV1 pid;
/* @@protoc_insertion_point(struct:tfcproto_SensorConfigV1) */
} tfcproto_SensorConfigV1;

typedef struct _tfcproto_RuntimeConfigV1 {
    uint32_t config_version;
    tfcproto_FanConfigV1 fan1;
    tfcproto_FanConfigV1 fan2;
    tfcproto_FanConfigV1 fan3;
    tfcproto_FanConfigV1 fan4;
    tfcproto_FanConfigV1 fan5;
    tfcproto_FanConfigV1 fan6;
    tfcproto_SensorConfigV1 temp_supply;
    tfcproto_SensorConfigV1 temp_return;
    tfcproto_SensorConfigV1 temp_case;
    tfcproto_SensorConfigV1 temp_aux1;
    tfcproto_SensorConfigV1 temp_aux2;
/* @@protoc_insertion_point(struct:tfcproto_RuntimeConfigV1) */
} tfcproto_RuntimeConfigV1;

/* Default values for struct fields */

/* Initializer values for message structs */
#define tfcproto_SensorConfigV1_init_default     {0, 0, 0, 0, tfcproto_PIDConfigV1_init_default}
#define tfcproto_FanConfigV1_init_default        {0, 0, _tfcproto_ControlMode_MIN, _tfcproto_ControlSource_MIN, 0, tfcproto_TableConfigV1_init_default}
#define tfcproto_TableConfigV1_init_default      {{tfcproto_TableConfigV1_TableEntryV1_init_default, tfcproto_TableConfigV1_TableEntryV1_init_default, tfcproto_TableConfigV1_TableEntryV1_init_default, tfcproto_TableConfigV1_TableEntryV1_init_default, tfcproto_TableConfigV1_TableEntryV1_init_default, tfcproto_TableConfigV1_TableEntryV1_init_default, tfcproto_TableConfigV1_TableEntryV1_init_default, tfcproto_TableConfigV1_TableEntryV1_init_default, tfcproto_TableConfigV1_TableEntryV1_init_default, tfcproto_TableConfigV1_TableEntryV1_init_default}}
#define tfcproto_TableConfigV1_TableEntryV1_init_default {0, 0}
#define tfcproto_PIDConfigV1_init_default        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, tfcproto_PIDStepV1_init_default, tfcproto_PIDStepV1_init_default}
#define tfcproto_PIDStepV1_init_default          {0, 0, 0}
#define tfcproto_RuntimeConfigV1_init_default    {0, tfcproto_FanConfigV1_init_default, tfcproto_FanConfigV1_init_default, tfcproto_FanConfigV1_init_default, tfcproto_FanConfigV1_init_default, tfcproto_FanConfigV1_init_default, tfcproto_FanConfigV1_init_default, tfcproto_SensorConfigV1_init_default, tfcproto_SensorConfigV1_init_default, tfcproto_SensorConfigV1_init_default, tfcproto_SensorConfigV1_init_default, tfcproto_SensorConfigV1_init_default}
#define tfcproto_SensorConfigV1_init_zero        {0, 0, 0, 0, tfcproto_PIDConfigV1_init_zero}
#define tfcproto_FanConfigV1_init_zero           {0, 0, _tfcproto_ControlMode_MIN, _tfcproto_ControlSource_MIN, 0, tfcproto_TableConfigV1_init_zero}
#define tfcproto_TableConfigV1_init_zero         {{tfcproto_TableConfigV1_TableEntryV1_init_zero, tfcproto_TableConfigV1_TableEntryV1_init_zero, tfcproto_TableConfigV1_TableEntryV1_init_zero, tfcproto_TableConfigV1_TableEntryV1_init_zero, tfcproto_TableConfigV1_TableEntryV1_init_zero, tfcproto_TableConfigV1_TableEntryV1_init_zero, tfcproto_TableConfigV1_TableEntryV1_init_zero, tfcproto_TableConfigV1_TableEntryV1_init_zero, tfcproto_TableConfigV1_TableEntryV1_init_zero, tfcproto_TableConfigV1_TableEntryV1_init_zero}}
#define tfcproto_TableConfigV1_TableEntryV1_init_zero {0, 0}
#define tfcproto_PIDConfigV1_init_zero           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, tfcproto_PIDStepV1_init_zero, tfcproto_PIDStepV1_init_zero}
#define tfcproto_PIDStepV1_init_zero             {0, 0, 0}
#define tfcproto_RuntimeConfigV1_init_zero       {0, tfcproto_FanConfigV1_init_zero, tfcproto_FanConfigV1_init_zero, tfcproto_FanConfigV1_init_zero, tfcproto_FanConfigV1_init_zero, tfcproto_FanConfigV1_init_zero, tfcproto_FanConfigV1_init_zero, tfcproto_SensorConfigV1_init_zero, tfcproto_SensorConfigV1_init_zero, tfcproto_SensorConfigV1_init_zero, tfcproto_SensorConfigV1_init_zero, tfcproto_SensorConfigV1_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define tfcproto_PIDStepV1_pct_tag               1
#define tfcproto_PIDStepV1_delay_tag             2
#define tfcproto_PIDStepV1_case_temp_delta_tag   3
#define tfcproto_TableConfigV1_TableEntryV1_temp_tag 1
#define tfcproto_TableConfigV1_TableEntryV1_pct_tag 2
#define tfcproto_PIDConfigV1_pwm_percent_min_tag 1
#define tfcproto_PIDConfigV1_pwm_percent_max1_tag 2
#define tfcproto_PIDConfigV1_pwm_percent_max2_tag 3
#define tfcproto_PIDConfigV1_setpoint_tag        4
#define tfcproto_PIDConfigV1_setpoint_min_tag    5
#define tfcproto_PIDConfigV1_setpoint_max_tag    6
#define tfcproto_PIDConfigV1_gain_p_tag          7
#define tfcproto_PIDConfigV1_gain_i_tag          8
#define tfcproto_PIDConfigV1_gain_d_tag          9
#define tfcproto_PIDConfigV1_adaptive_sp_tag     10
#define tfcproto_PIDConfigV1_adaptive_sp_check_case_temp_tag 11
#define tfcproto_PIDConfigV1_adaptive_sp_step_size_tag 12
#define tfcproto_PIDConfigV1_adaptive_sp_step_down_tag 13
#define tfcproto_PIDConfigV1_adaptive_sp_step_up_tag 14
#define tfcproto_TableConfigV1_entries_tag       1
#define tfcproto_FanConfigV1_pin_pwm_tag         1
#define tfcproto_FanConfigV1_pin_rpm_tag         2
#define tfcproto_FanConfigV1_mode_tag            3
#define tfcproto_FanConfigV1_source_tag          4
#define tfcproto_FanConfigV1_ratio_tag           5
#define tfcproto_FanConfigV1_tbl_tag             6
#define tfcproto_SensorConfigV1_pin_tag          1
#define tfcproto_SensorConfigV1_beta_tag         2
#define tfcproto_SensorConfigV1_series_r_tag     3
#define tfcproto_SensorConfigV1_nominal_r_tag    4
#define tfcproto_SensorConfigV1_pid_tag          5
#define tfcproto_RuntimeConfigV1_config_version_tag 1
#define tfcproto_RuntimeConfigV1_fan1_tag        2
#define tfcproto_RuntimeConfigV1_fan2_tag        3
#define tfcproto_RuntimeConfigV1_fan3_tag        4
#define tfcproto_RuntimeConfigV1_fan4_tag        5
#define tfcproto_RuntimeConfigV1_fan5_tag        6
#define tfcproto_RuntimeConfigV1_fan6_tag        7
#define tfcproto_RuntimeConfigV1_temp_supply_tag 8
#define tfcproto_RuntimeConfigV1_temp_return_tag 9
#define tfcproto_RuntimeConfigV1_temp_case_tag   10
#define tfcproto_RuntimeConfigV1_temp_aux1_tag   11
#define tfcproto_RuntimeConfigV1_temp_aux2_tag   12

/* Struct field encoding specification for nanopb */
extern const pb_field_t tfcproto_SensorConfigV1_fields[6];
extern const pb_field_t tfcproto_FanConfigV1_fields[7];
extern const pb_field_t tfcproto_TableConfigV1_fields[2];
extern const pb_field_t tfcproto_TableConfigV1_TableEntryV1_fields[3];
extern const pb_field_t tfcproto_PIDConfigV1_fields[15];
extern const pb_field_t tfcproto_PIDStepV1_fields[4];
extern const pb_field_t tfcproto_RuntimeConfigV1_fields[13];

/* Maximum encoded size of messages (where known) */
#define tfcproto_SensorConfigV1_size             130
#define tfcproto_FanConfigV1_size                165
#define tfcproto_TableConfigV1_size              140
#define tfcproto_TableConfigV1_TableEntryV1_size 12
#define tfcproto_PIDConfigV1_size                104
#define tfcproto_PIDStepV1_size                  18
#define tfcproto_RuntimeConfigV1_size            1679

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define RUNTIME_CONFIG_V1_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
