/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Fri Feb 28 14:33:11 2020. */

#include "runtime_config_v1.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t tfcproto_SensorConfigV1_fields[6] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, tfcproto_SensorConfigV1, pin, pin, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_SensorConfigV1, beta, pin, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_SensorConfigV1, series_r, beta, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_SensorConfigV1, nominal_r, series_r, 0),
    PB_FIELD(  5, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_SensorConfigV1, pid, nominal_r, &tfcproto_PIDConfigV1_fields),
    PB_LAST_FIELD
};

const pb_field_t tfcproto_FanConfigV1_fields[7] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, tfcproto_FanConfigV1, pin_pwm, pin_pwm, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_FanConfigV1, pin_rpm, pin_pwm, 0),
    PB_FIELD(  3, UENUM   , SINGULAR, STATIC  , OTHER, tfcproto_FanConfigV1, mode, pin_rpm, 0),
    PB_FIELD(  4, UENUM   , SINGULAR, STATIC  , OTHER, tfcproto_FanConfigV1, source, mode, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_FanConfigV1, ratio, source, 0),
    PB_FIELD(  6, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_FanConfigV1, tbl, ratio, &tfcproto_TableConfigV1_fields),
    PB_LAST_FIELD
};

const pb_field_t tfcproto_TableConfigV1_fields[2] = {
    PB_REPEATED_FIXED_COUNT(  1, MESSAGE , FIRST, tfcproto_TableConfigV1, entries, entries, &tfcproto_TableConfigV1_TableEntryV1_fields),
    PB_LAST_FIELD
};

const pb_field_t tfcproto_TableConfigV1_TableEntryV1_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, tfcproto_TableConfigV1_TableEntryV1, temp, temp, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_TableConfigV1_TableEntryV1, pct, temp, 0),
    PB_LAST_FIELD
};

const pb_field_t tfcproto_PIDConfigV1_fields[15] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, tfcproto_PIDConfigV1, pwm_percent_min, pwm_percent_min, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_PIDConfigV1, pwm_percent_max1, pwm_percent_min, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_PIDConfigV1, pwm_percent_max2, pwm_percent_max1, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_PIDConfigV1, setpoint, pwm_percent_max2, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_PIDConfigV1, setpoint_min, setpoint, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_PIDConfigV1, setpoint_max, setpoint_min, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_PIDConfigV1, gain_p, setpoint_max, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_PIDConfigV1, gain_i, gain_p, 0),
    PB_FIELD(  9, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_PIDConfigV1, gain_d, gain_i, 0),
    PB_FIELD( 10, BOOL    , SINGULAR, STATIC  , OTHER, tfcproto_PIDConfigV1, adaptive_sp, gain_d, 0),
    PB_FIELD( 11, BOOL    , SINGULAR, STATIC  , OTHER, tfcproto_PIDConfigV1, adaptive_sp_check_case_temp, adaptive_sp, 0),
    PB_FIELD( 12, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_PIDConfigV1, adaptive_sp_step_size, adaptive_sp_check_case_temp, 0),
    PB_FIELD( 13, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_PIDConfigV1, adaptive_sp_step_down, adaptive_sp_step_size, &tfcproto_PIDStepV1_fields),
    PB_FIELD( 14, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_PIDConfigV1, adaptive_sp_step_up, adaptive_sp_step_down, &tfcproto_PIDStepV1_fields),
    PB_LAST_FIELD
};

const pb_field_t tfcproto_PIDStepV1_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, tfcproto_PIDStepV1, pct, pct, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_PIDStepV1, delay, pct, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, tfcproto_PIDStepV1, case_temp_delta, delay, 0),
    PB_LAST_FIELD
};

const pb_field_t tfcproto_RuntimeConfigV1_fields[13] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, tfcproto_RuntimeConfigV1, config_version, config_version, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_RuntimeConfigV1, fan1, config_version, &tfcproto_FanConfigV1_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_RuntimeConfigV1, fan2, fan1, &tfcproto_FanConfigV1_fields),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_RuntimeConfigV1, fan3, fan2, &tfcproto_FanConfigV1_fields),
    PB_FIELD(  5, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_RuntimeConfigV1, fan4, fan3, &tfcproto_FanConfigV1_fields),
    PB_FIELD(  6, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_RuntimeConfigV1, fan5, fan4, &tfcproto_FanConfigV1_fields),
    PB_FIELD(  7, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_RuntimeConfigV1, fan6, fan5, &tfcproto_FanConfigV1_fields),
    PB_FIELD(  8, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_RuntimeConfigV1, temp_supply, fan6, &tfcproto_SensorConfigV1_fields),
    PB_FIELD(  9, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_RuntimeConfigV1, temp_return, temp_supply, &tfcproto_SensorConfigV1_fields),
    PB_FIELD( 10, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_RuntimeConfigV1, temp_case, temp_return, &tfcproto_SensorConfigV1_fields),
    PB_FIELD( 11, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_RuntimeConfigV1, temp_aux1, temp_case, &tfcproto_SensorConfigV1_fields),
    PB_FIELD( 12, MESSAGE , SINGULAR, STATIC  , OTHER, tfcproto_RuntimeConfigV1, temp_aux2, temp_aux1, &tfcproto_SensorConfigV1_fields),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(tfcproto_SensorConfigV1, pid) < 65536 && pb_membersize(tfcproto_FanConfigV1, tbl) < 65536 && pb_membersize(tfcproto_TableConfigV1, entries[0]) < 65536 && pb_membersize(tfcproto_PIDConfigV1, adaptive_sp_step_down) < 65536 && pb_membersize(tfcproto_PIDConfigV1, adaptive_sp_step_up) < 65536 && pb_membersize(tfcproto_RuntimeConfigV1, fan1) < 65536 && pb_membersize(tfcproto_RuntimeConfigV1, fan2) < 65536 && pb_membersize(tfcproto_RuntimeConfigV1, fan3) < 65536 && pb_membersize(tfcproto_RuntimeConfigV1, fan4) < 65536 && pb_membersize(tfcproto_RuntimeConfigV1, fan5) < 65536 && pb_membersize(tfcproto_RuntimeConfigV1, fan6) < 65536 && pb_membersize(tfcproto_RuntimeConfigV1, temp_supply) < 65536 && pb_membersize(tfcproto_RuntimeConfigV1, temp_return) < 65536 && pb_membersize(tfcproto_RuntimeConfigV1, temp_case) < 65536 && pb_membersize(tfcproto_RuntimeConfigV1, temp_aux1) < 65536 && pb_membersize(tfcproto_RuntimeConfigV1, temp_aux2) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_tfcproto_SensorConfigV1_tfcproto_FanConfigV1_tfcproto_TableConfigV1_tfcproto_TableConfigV1_TableEntryV1_tfcproto_PIDConfigV1_tfcproto_PIDStepV1_tfcproto_RuntimeConfigV1)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(tfcproto_SensorConfigV1, pid) < 256 && pb_membersize(tfcproto_FanConfigV1, tbl) < 256 && pb_membersize(tfcproto_TableConfigV1, entries[0]) < 256 && pb_membersize(tfcproto_PIDConfigV1, adaptive_sp_step_down) < 256 && pb_membersize(tfcproto_PIDConfigV1, adaptive_sp_step_up) < 256 && pb_membersize(tfcproto_RuntimeConfigV1, fan1) < 256 && pb_membersize(tfcproto_RuntimeConfigV1, fan2) < 256 && pb_membersize(tfcproto_RuntimeConfigV1, fan3) < 256 && pb_membersize(tfcproto_RuntimeConfigV1, fan4) < 256 && pb_membersize(tfcproto_RuntimeConfigV1, fan5) < 256 && pb_membersize(tfcproto_RuntimeConfigV1, fan6) < 256 && pb_membersize(tfcproto_RuntimeConfigV1, temp_supply) < 256 && pb_membersize(tfcproto_RuntimeConfigV1, temp_return) < 256 && pb_membersize(tfcproto_RuntimeConfigV1, temp_case) < 256 && pb_membersize(tfcproto_RuntimeConfigV1, temp_aux1) < 256 && pb_membersize(tfcproto_RuntimeConfigV1, temp_aux2) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_tfcproto_SensorConfigV1_tfcproto_FanConfigV1_tfcproto_TableConfigV1_tfcproto_TableConfigV1_TableEntryV1_tfcproto_PIDConfigV1_tfcproto_PIDStepV1_tfcproto_RuntimeConfigV1)
#endif


/* @@protoc_insertion_point(eof) */
